-- AlterTable
ALTER TABLE "Culture_Test" ALTER COLUMN "result" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Culture_Type" ALTER COLUMN "lower_end" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "upper_end" SET DATA TYPE DOUBLE PRECISION;
